### ISSUE TITLE
Plans to upgrade material-ui

### ISSUE THREAD

**Issue by danielbe1** [kinoplan/scalajs-react-material-ui#26]
Are there any plans to upgrade to a newer version of material-ui? Are there specific hurdles, or is this something that can even I as a newcomer can contribute to the project?

**Comment by kazievab** [comment]
Hi! Yes, I was planning to do it soon. As far as I know there are a few things that may be difficult, so I think it will not be easy.

**Comment by danielbe1** [comment]
Great to hear, ill be looking forward to the update!

**Comment by tomasherman** [comment]
hello, any progress on this? im trying to figure out whether to write my own bridges or reuse what you've already built which seems like a great collection of stuff :)

**Comment by kazievab** [comment]
Hello. I was able to start this only a week ago, but yes, progress has begun :)
