### ISSUE TITLE
CSS style tag precedence.

### ISSUE THREAD

**Issue by danielbe1** [kinoplan/scalajs-react-material-ui#27]
I am attempting to apply css transitions to a material-ui AppBar that affect its width, however, it seems that the style for AppBar is being registered after my own CSS styles causing the width attribute to not change.

I managed to fix this behavior by marking the styles as important, but is there a way to make sure that the material-ui styles are registered before my own styles?

**Comment by kazievab** [comment]
You need to apply styles after calling renderIntoDom like here - https://github.com/kinoplan/scalajs-react-material-ui/blob/master/demo/src/main/scala/io/kinoplan/demo/AppMain.scala#L13
